Variables to CLI args, be aware of paths /w spaces

diff --git a/publish b/publish
--- a/publish
+++ b/publish
@@ -1,4 +1,4 @@
-#!/bin/sh -ef
+#!/bin/bash -ef
 
 # publish: publishes build results to a certain repository.
 #
@@ -17,9 +17,77 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-GH_USER=kaitai-io
-GH_REPO_NAME=ci_artifacts
-GH_REPO_BRANCH="$TARGET$SUBTARGET/$VARIETY"
+usage()
+{
+	echo "Usage: $0 -o <login> -r <name> [ -b <name> ] [ -x=<path> ]... <srcdir>... | --help"
+	echo
+	echo "Example: $0 -o kaitai-io -r ci_artifacts -b my-branch -x=.git -x=.travis.yml tests/test_out"
+	echo
+	echo 'Options:'
+	echo
+	echo '  -o, --owner <login>'
+	echo '          login of the GitHub user or organization which owns the target repository'
+	echo
+	echo '  -r, --repo <name>'
+	echo '          name of the target repository'
+	echo
+	echo '  -b, --branch <name>'
+	echo '          branch of the target repository to which to publish (optional)'
+	echo
+	echo '  -x=, --exclude=<path>'
+	echo '          exclude path from being published (optional)'
+}
+
+include_paths=()
+exclude_args=()
+while [ "$1" != "" ]; do
+	case $1 in
+		-o | --owner )
+			shift
+			owner=$1
+			;;
+		-r | --repo )
+			shift
+			repo=$1
+			;;
+		-b | --branch )
+			shift
+			branch=$1
+			;;
+		-x=* | --exclude=* )
+			exclude_args+=("--exclude=${1#*=}")
+			;;
+		-h | --help )
+			usage
+			exit
+			;;
+		* )
+			include_paths+=("$1")
+			;;
+	esac
+	shift
+done
+
+if [ ${#include_paths[@]} -eq 0 ]; then
+	echo "Error: you must specify at least one <srcdir> to publish"
+	echo
+	usage
+	exit 1
+fi
+
+if [ -z "$owner" ]; then
+	echo 'Error: missing option -o (--owner)'
+	echo
+	usage
+	exit 1
+fi
+
+if [ -z "$repo" ]; then
+	echo 'Error: missing option -r (--repo)'
+	echo
+	usage
+	exit 1
+fi
 
 export GIT_AUTHOR_NAME='Kaitai Bot'
 export GIT_AUTHOR_EMAIL='kaitai-bot@kaitai.io'
@@ -34,12 +102,12 @@ fi
 unset SSH_AGENT_PID SSH_AUTH_SOCK
 
 echo -n 'Setting up bot key... '
-echo "$BOT_SSH_KEY" | base64 --decode >$HOME/bot_id
-chmod 600 $HOME/bot_id
+echo "$BOT_SSH_KEY" | base64 --decode > "$HOME"/bot_id
+chmod 600 "$HOME"/bot_id
 echo OK
 
 echo -n 'Checking if key looks valid... '
-key_head=$(head -n1 $HOME/bot_id)
+key_head=$(head -n1 "$HOME"/bot_id)
 if [ "$key_head" != '-----BEGIN RSA PRIVATE KEY-----' ]; then
 	echo 'Nope, key seems to be invalid'
 	exit 1
@@ -47,12 +115,12 @@ fi
 echo -n 'OK, '
 
 echo 'Setting up known_hosts'
-mkdir -p $HOME/.ssh
-chmod 700 $HOME/.ssh
+mkdir -p "$HOME"/.ssh
+chmod 700 "$HOME"/.ssh
 need_add_ssh_key=0
 if [ -f "$HOME/.ssh/known_hosts" ]; then
 	echo '... it already exists:'
-	cat $HOME/.ssh/known_hosts
+	cat "$HOME"/.ssh/known_hosts
 	if grep -q '^github.com ssh-rsa ' "$HOME/.ssh/known_hosts"; then
 		need_add_ssh_key=0
 	else
@@ -65,12 +133,12 @@ fi
 
 if [ "$need_add_ssh_key" = 1 ]; then
 	echo '... setting up github.com key'
-	echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >>$HOME/.ssh/known_hosts
+	echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> $HOME/.ssh/known_hosts
 fi
 
 # Dump bot_id SHA1 to check key validity. Linux uses "sha1sum", OS X uses
 # "shasum", but even if both fails, it's not super critical.
-sha1sum $HOME/bot_id || shasum $HOME/bot_id || :
+sha1sum "$HOME"/bot_id || shasum "$HOME"/bot_id || :
 
 # Alas, it seems that Travis CI uses ancient git that doesn't support this
 #export GIT_SSH_COMMAND="ssh -i $HOME/bot_id"
@@ -79,22 +147,22 @@ sha1sum $HOME/bot_id || shasum $HOME/bot_id || :
 git config --global push.default simple
 
 echo -n 'Setting up ssh wrapper... '
-cat >$HOME/git-ssh <<__EOF__
+cat >"$HOME"/git-ssh <<__EOF__
 #!/bin/sh -efx
 ssh -i "$HOME/bot_id" "\$@"
 __EOF__
-chmod a+x $HOME/git-ssh
+chmod a+x "$HOME"/git-ssh
 export GIT_SSH="$HOME/git-ssh"
 echo 'OK'
 
 echo 'Cloning website repo...'
-if git clone --branch="$GH_REPO_BRANCH" git@github.com:"$GH_USER"/"$GH_REPO_NAME".git; then
+if git clone --branch="$branch" git@github.com:"$owner"/"$repo".git; then
 	echo "OK"
 else
 	echo "Branch seems to be not available => trying to create it"
-	git clone git@github.com:"$GH_USER"/"$GH_REPO_NAME".git
-	cd "$GH_REPO_NAME"
-	git checkout -b "$GH_REPO_BRANCH"
+	git clone git@github.com:"$owner"/"$repo".git
+	cd "$repo"
+	git checkout -b "$branch"
 	cd ..
 fi
 
@@ -109,15 +177,16 @@ else
 fi
 
 echo 'Updating the files...'
-"$RSYNC_BIN" --delete-after -c --exclude=.git --exclude=.travis.yml -r -v tests/test_out "$GH_REPO_NAME"
+$exclude_dirs
+"$RSYNC_BIN" --delete-after -c "${exclude_args[@]}" -r -v "${include_paths[@]}" "$repo"
 
 echo 'Adding and committing...'
-cd "$GH_REPO_NAME"
+cd "$repo"
 git add --all .
 git commit -m "Submitted results from Travis build"
 
 echo 'Pushing...'
-git push -u origin "$GH_REPO_BRANCH"
+git push -u origin "$branch"
 
 echo -n 'Cleaning up the key and wrapper... '
 rm "$HOME/bot_id" "$HOME/git-ssh"
